% Oliver Gordon, 4224942
% Ballistic Project
clear all
close all

% Input data
l = [8,16,32,64,128,256];
ln_l = log(l);
e0 = [1.374,2.142,2.984,4.165,5.773,7.661];
delta_e0 = [0.003,0.004,0.006,0.032,0.064,0.134];
ln_e0 = log(e0);
ln_delta_e0_neg = 0.8*log(e0-delta_e0);
ln_delta_e0_pos = log(e0+delta_e0);

% Plot
hold on
errorbar(ln_l,ln_e0,delta_e0,'x');

%% Code generated by cftool
[xData, yData, weights] = prepareCurveData( ln_l, ln_e0, ln_delta_e0_neg );

% Set up fittype and options.
ft = fittype( 'a*x+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.959813292877761 0.414119221850809];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
h = plot( fitresult, xData, yData );

xlabel('$ln(l)$','Interpreter','LaTex');
ylabel('$ln(\bar{h})$','Interpreter','LaTex');